config/routes.rb
Rails.application.routes.draw do
  root 'activities#index'

  get '/auth/strava/callback' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'map', to: 'maps#index'

  namespace :admin do
    root 'dashboard#index'
    resources :activities, only: [ :new, :create, :edit, :update ]
  end

  get ':id', to: 'activities#show', as: :activity
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  extend FriendlyId

  serialize :strava_data, ActiveRecord::Coders::NestedHstore
  serialize :strava_streams_data, ActiveRecord::Coders::NestedHstore
  friendly_id :title, use: :slugged
end

app/models/activity_form.rb
class ActivityForm
  include ActiveModel::Model
  attr_accessor :strava_activity_id, :strava_segment_id, :title, :body

  validates :body, :title, presence: true

  def self.model_name
    Activity.model_name
  end

  def body
    defined?(@body) ? @body : strava_data.activity_data[:description]
  end

  def title
    defined?(@title) ? @title : strava_data.activity_data[:name]
  end

  def persisted?
    id.present?
  end

  def id
    existing_activity.try(:id)
  end

  def save
    if valid?
      persisted? ? update : create
    end
  end

  def has_no_strava_data?
    !strava_data.valid?
  end

  def segment_collection
    strava_data.activity_data[:segment_efforts].map { |segment_effort| [segment_effort['name'], segment_effort['segment']['id']] }.uniq
  end

  private

  def update
    existing_activity.update_attributes!({
      title: title,
      body: body,
      strava_segment_id: strava_segment_id
    })
  end

  def create
    Activity.create!({
      title: title,
      body: body,
      strava_activity_id: strava_activity_id,
      strava_segment_id: strava_segment_id,
      strava_data: strava_data.activity_data,
      strava_streams_data: strava_data.streams_data,
      created_at: Time.parse(strava_data.activity_data[:start_date_local]),
      updated_at: Time.now
    })
  end

  def existing_activity
    Activity.where(strava_activity_id: strava_activity_id).first
  end

  def strava_data
    @strava_data ||= StravaData.new(strava_activity_id)
  end
end

app/models/activity_stats.rb
class ActivityStats < Struct.new(:activity)
  def moving_time
    formatted_duration(strava_data[:moving_time].to_i)
  end

  def metres_climbed
    "#{strava_data[:total_elevation_gain].to_i} metres"
  end

  def average_speed
    "#{(strava_data[:average_speed].to_f * 3.6).round(2)} km/h"
  end

  def distance
    "#{(strava_data[:distance].to_f / 1000).round(2)} km"
  end

  private

  def formatted_duration(seconds)
    Time.at(seconds).utc.strftime("%H:%M:%S")
  end

  def strava_data
    activity.strava_data.with_indifferent_access
  end
end

app/models/strava_data.rb
class StravaData
  STREAM_TYPES = %w(time latlng distance altitude velocity_smooth grade_smooth).join(',')

  def initialize(activity_id)
    @activity_id = activity_id
  end

  def activity_data
    @activity_data ||= cached_activity_data || fetch_activity_data
  end

  def streams_data
    @streams_data ||= cached_streams_data || fetch_streams_data
  end

  def valid?
    activity_data.present?
  end

  private

  def fetch_activity_data
    @activity_id.presence && STRAVA_API_CLIENT.retrieve_an_activity(@activity_id).with_indifferent_access.tap do |data|
      Rails.cache.write(activity_cache_key, data)
    end
  rescue Strava::Api::V3::ClientError => e
    errors.add(:strava_activity_id, e.message)
    nil
  end

  def fetch_streams_data
    @activity_id.presence && { streams: STRAVA_API_CLIENT.retrieve_activity_streams(@activity_id, STREAM_TYPES).map(&:with_indifferent_access) }.tap do |data|
      Rails.cache.write(streams_cache_key, data)
    end
  rescue Strava::Api::V3::ClientError => e
    errors.add(:strava_activity_id, e.message)
    nil
  end

  def cached_activity_data
    Rails.cache.fetch(activity_cache_key)
  end

  def cached_streams_data
    Rails.cache.fetch(streams_cache_key)
  end

  def activity_cache_key
    "strava_activity_#{@activity_id}"
  end

  def streams_cache_key
    "strava_activity_streams_#{@activity_id}_#{STREAM_TYPES}"
  end
end

app/models/title.rb
class Title
  def initialize(page_title)
    @page_title = page_title
  end

  def to_s
    [blog_title, @page_title].compact.join(' || ')
  end

  def blog_title
    ENV['BLOG_TITLE']
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Activity.order('created_at desc').map { |activity| ActivityPresenter.new(activity) }
  end

  def show
    activity = Activity.friendly.find(params[:id])
    @activity_presenter = ActivityPresenter.new(activity)
    @activity_stats = ActivityStats.new(activity)
    @page_title = activity.title
  end
end

app/controllers/admin/activities_controller.rb
class Admin::ActivitiesController < Admin::BaseController
  def new
    @activity_form = ActivityForm.new(activity_params)

    if @activity_form.has_no_strava_data?
      redirect_to admin_root_path, flash: { alert: @activity_form.errors.full_messages.to_sentence }
    end
  end

  def create
    @activity_form = ActivityForm.new(activity_params)

    if @activity_form.save
      redirect_to admin_root_path, flash: { notice: 'Created new activity' }
    else
      render :new
    end
  end

  def edit
    @activity = Activity.friendly.find(params[:id])
    @activity_form = ActivityForm.new(@activity.attributes.with_indifferent_access.slice(:title, :body, :strava_activity_id, :strava_segment_id))
  end

  def update
    @activity_form = ActivityForm.new(activity_params)

    if @activity_form.save
      redirect_to admin_root_path, flash: { notice: 'Updated activity' }
    else
      render :edit
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:title, :body, :strava_activity_id, :strava_segment_id)
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :ensure_logged_in

  private

  def ensure_logged_in
    unless authenticated_session.signed_in?
      redirect_to '/auth/strava'
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
    @acitivities_count = Activity.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def authenticated_session
    @authenticated_session ||= Concerns::AuthenticatedSession.new(session)
  end
  helper_method :authenticated_session

  def title_presenter
    @title_presenter ||= TitlePresenter.new(@page_title)
  end
  helper_method :title_presenter
end

app/controllers/concerns/authenticated_session.rb
class Concerns::AuthenticatedSession
  def initialize(storage)
    @storage = storage
  end

  def create(strava_auth_token)
    @storage[:strava_auth_token] = strava_auth_token
  end

  def delete
    @storage[:strava_auth_token] = nil
  end

  def signed_in?
    @storage[:strava_auth_token].present?
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
    @activities = Activity.all.map { |activity| ActivityPresenter.new(activity) }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if authentication_successful?
      authenticated_session.create(strava_auth_token)
      flash[:notice] = 'Logged in, well done!'
      redirect_to admin_root_path
    else
      flash[:alert] = 'Unable to login, sorry'
      redirect_to root_path
    end
  end

  def destroy
    authenticated_session.delete

    redirect_to root_path
  end

  private

  def authentication_successful?
    strava_athlete_id == owner_strava_athlete_id
  end

  def owner_strava_athlete_id
    ENV['STRAVA_ATHELETE_ID'].to_i
  end

  def strava_athlete_id
    @strava_athlete_id ||= auth_hash[:uid].to_i
  end

  def strava_auth_token
    auth_hash.fetch(:credentials, { }).fetch(:token, nil)
  end

  def auth_hash
    request.env.fetch('omniauth.auth', { })
  end
end

app/views/activities/_activity.html.erb
<div class="activity">
  <h2 class="activity__title">
    <%= link_to activity do %>
      <span class="activity__date"><%= activity.date %></span> - 
      <%= activity.title %>
    <% end %>
  </h2>

  <div class="activity__body">
    <%= activity.short_summary_paragraphs(3) { link_to('read more', activity) }%>
  </div>
</div>

app/views/activities/_data.html.erb
<div class="activity__map" data-map></div>

app/views/activities/_graphs.html.erb
<div class="activity__graph__laps"></div>
<div class="activity__graph__altitude"></div>
<div class="activity__graph__velocity"></div>

<script type="text/javascript">
  window.streamData = <%= activity_presenter.streams_json.html_safe %>;
  window.lapData = <%= activity_presenter.laps_json.html_safe %>;
</script>

app/views/activities/index.html.erb
<%= render partial: 'activity', collection: @activities %>

app/views/activities/show.html.erb
<% provide :navigation_items do %>
  <% if authenticated_session.signed_in? %>
    <%= NavigationItemPresenter.new('edit', edit_admin_activity_path(@activity_presenter.activity)).to_s %>
  <% end %>
<% end %>

<div class="activity">
  <h2 class="activity__title">
    <span class="activity__date"><%= @activity_presenter.date %></span> - 
    <%= @activity_presenter.title %>
  </h2>

  <div class="activity__body">
    <%= simple_format(@activity_presenter.body) %>
  </div>

  <table class="activity__stats">
    <tr>
      <th class="activity__stats__heading">Moving Time:</th>
      <td class="activity__stats__stat"><%= @activity_stats.moving_time %></td>
    </tr>
    <tr>
      <th class="activity__stats__heading">Distance:</th>
      <td class="activity__stats__stat"><%= @activity_stats.distance %></td>
    </tr>
    <tr>
      <th class="activity__stats__heading">Average Speed:</th>
      <td class="activity__stats__stat"><%= @activity_stats.average_speed %></td>
    </tr>
    <tr>
      <th class="activity__stats__heading">Climbed:</th>
      <td class="activity__stats__stat"><%= @activity_stats.metres_climbed %></td>
    </tr>
  </table>

  <%= render :partial => 'data', locals: { activity_presenter: @activity_presenter } %>
  <%= render :partial => 'graphs', locals: { activity_presenter: @activity_presenter } %>
</div>

app/views/admin/activities/_form.html.erb
<%= simple_form_for [ :admin, activity_form ] do |form| %>
  <%= form.input :title %>
  <%= form.input :body, as: :text, input_html: { rows: 20 } %>
  <%= form.input :strava_activity_id, as: :hidden %>
  <%= form.input :strava_segment_id, collection: activity_form.segment_collection, hint: '(Optional) Select segment for lapped races' %>

  <%= form.submit activity_form.persisted? ? 'Update Activity' : 'Create Activity', class: 'button' %>
<% end %>

app/views/admin/activities/edit.html.erb
<h2>Edit Activity</h2>

<%= render partial: 'form', locals: { activity_form: @activity_form } %>

app/views/admin/activities/new.html.erb
<h2>New Activity</h2>

<%= render partial: 'form', locals: { activity_form: @activity_form } %>

app/views/admin/dashboard/index.html.erb
<div class="blog__navigation">
  <% if authenticated_session.signed_in? %>
    <p class="blog__navigation__item"><%= link_to('homepage', root_path) %></p>
    <p class="blog__navigation__item"><%= link_to 'logout', logout_path, method: 'delete' %></p>
  <% end %>
</div>

<p>You currently have <%= @acitivities_count %> activities.</p>

<p>Create a new activity</p>
<%= simple_form_for ActivityForm.new, :url => new_admin_activity_path, :method => :get  do |form| %>
  <%= form.input :strava_activity_id, :label => 'Strava Activity ID' %>
  <%= form.submit 'Create new activity', :class => 'button' %>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice].present? %>
  <div data-alert class='alert-box success radius'>
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert].present? %>
  <div data-alert class='alert-box alert radius'>
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="blog__navigation">
  <%= NavigationItemPresenter.new('home', root_path, current_page?(root_path)).to_s %>
  <%= NavigationItemPresenter.new('map', map_path, current_page?(map_path)).to_s %>

  <% if authenticated_session.signed_in? %>
    <%= NavigationItemPresenter.new('admin dashboard', admin_root_path, current_page?(admin_root_path)).to_s %>
  <% end %>
  <%= yield :navigation_items %>
</div>

app/views/layouts/_title.html.erb
<h1 class="blog__title">
  <% if current_page?(root_path) %>
    <%= title_presenter.blog_title %>
  <% else %>
    <%= link_to(title_presenter.blog_title, root_path) %>
  <% end %>
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= title_presenter %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag '//maps.googleapis.com/maps/api/js?v=3.exp&libraries=geometry' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render :partial => 'layouts/flash' %>
    <%= render :partial => 'layouts/title' %>
    <%= render :partial => 'layouts/navigation' %>

    <script>
      window.streamData = null;
      window.lapData = null;
    </script>

    <%= yield %>
  </body>
</html>

app/views/maps/index.html.erb
<div class="map">
  <div class="map__canvas" data-all-map data-polylines='<%= @activities.map(&:polyline).compact.to_json.html_safe %>'</div>
</div>